/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00112e",
        "primary-container": "#10264a",
        "on-primary": "#ffffff",
        "on-primary-container": "#7a8eb8",
        "secondary": "#964900",
        "secondary-container": "#ff8928",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#642f00",
        "tertiary": "#02122b",
        "tertiary-container": "#172740",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7f8ead",
        "background": "#f9f9ff",
        "on-background": "#121b2e",
        "surface": "#f9f9ff",
        "on-surface": "#121b2e",
        "on-surface-variant": "#44474e",
        "surface-container": "#e9edff",
        "surface-container-low": "#f1f3ff",
        "surface-container-high": "#e1e8ff",
        "surface-container-highest": "#d9e2fc",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d1daf4",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#d9e2fc",
        "outline": "#75777f",
        "outline-variant": "#c5c6cf",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "brand-orange": "#F58220",
        "brand-navy": "#10264A",
        "brand-dark-navy": "#091A33"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'container-max': '1440px',
        'gutter': '24px',
      }
    },
  },
  plugins: [],
}
